Implement function to de-flat objects by nested keys concatenation with 1st level keys
metarhia/metautil pull request #117
Opened 2022-07-28 00:06 UTC by Fr3ud

- [x] tests and linter show no problems (`npm t`)
- [x] tests are added/updated for bug fixes and new features
- [x] code is properly formatted (`npm run fmt`)
- [ ] description of changes is added in CHANGELOG.md
- [ ] update .d.ts typings

2022-07-28 12:13 UTC, tshemsedinov commented
Give commit tiples max 50 chars long. And short (1 line) PR titles. @Fr3ud

2022-07-28 12:42 UTC, Fr3ud commented
@tshemsedinov, done

2022-07-28 17:17 UTC, georgolden requested changes

2022-07-28 17:25 UTC, tshemsedinov commented on CHANGELOG.md
> +- Add function `deflatObject(source: object, fieldName: string): object`
```suggestion
- Add function `unflatObject(source: object, fieldNames: Array<string>): object`
```

2022-07-28 17:25 UTC, tshemsedinov commented on lib/utilities.js
> +const deflatObject = (source, fieldName) => {
`fieldNames` is required paramater

2022-07-28 17:25 UTC, tshemsedinov commented on lib/utilities.js
> +        if (inRange(key[i], 'A', 'Z')) {
Do not iterate by chars, just `for (const prefix of fieldNames)` and use `startsWith`

2022-07-28 17:25 UTC, tshemsedinov commented on lib/utilities.js
> +    if (fieldName && typeof value === 'object' && !Array.isArray(value)) {
We do not support arrays

2022-08-02 16:25 UTC, tshemsedinov commented on lib/utilities.js
> +    }
```suggestion
    if (key.startsWith(prefix)) return prefix;
```

2022-08-02 16:25 UTC, tshemsedinov commented on lib/utilities.js
> +    const prefix = getPrefix(key, fieldNames);
Use .find

2022-08-02 16:25 UTC, tshemsedinov commented on lib/utilities.js
> +      if (source[prefix] !== undefined) {
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty

2022-08-02 16:25 UTC, tshemsedinov commented on lib/utilities.js
> +      }
```suggestion
      result[prefix] = result[prefix] || {};
```

2022-08-04 17:20 UTC, tshemsedinov commented
See https://github.com/metarhia/metautil/pull/115 to resolve conflicts with landed `isHashObject`

2022-08-06 07:34 UTC, tshemsedinov commented on lib/utilities.js
> +      // eslint-disable-next-line no-prototype-builtins
```suggestion
```

2022-08-06 07:35 UTC, tshemsedinov commented on lib/utilities.js
> +    const prefix = fieldNames.find((prefix) => key.startsWith(prefix));
```suggestion
    const prefix = fieldNames.find((name) => key.startsWith(name));
```

2022-08-06 07:40 UTC, tshemsedinov commented on lib/utilities.js
> +      if (sourceObject.hasOwnProperty(prefix)) {
```suggestion
      if (Object.prototype.hasOwnProperty.call(sourceObject, prefix) {
```

2022-08-06 07:40 UTC, tshemsedinov commented on lib/utilities.js
> +
```suggestion
```

2022-08-06 07:40 UTC, tshemsedinov commented on lib/utilities.js
> +
```suggestion
```

2022-08-06 07:40 UTC, tshemsedinov commented on lib/utilities.js
> +
```suggestion
      const newKey = key.slice(prefix.length).toLowerCase();
```

2022-08-06 07:40 UTC, tshemsedinov commented on lib/utilities.js
> +
```suggestion
```

2022-08-06 07:40 UTC, tshemsedinov commented on lib/utilities.js
> +        }
```suggestion
        if (Object.prototype.hasOwnProperty.call(sourceObject, newKey)) {
          throw new Error(
            `Can not combine keys: key "${newKey}" already exists`,
          );
        }
```

2022-08-06 07:40 UTC, tshemsedinov commented on lib/utilities.js
> +};
```suggestion
        result[newKey] = nestedValue;
      }
      continue;
    }
    result[key] = value;
  }
  return result;
};
```

2022-08-06 07:46 UTC, tshemsedinov commented on lib/utilities.js
> +      result[prefix][newKey] = value;
```suggestion
      const newKey = key.slice(prefix.length).toLowerCase();
      const section = result[prefix];
      if (section) section[newKey] = value;
      else result[prefix] = { [newKey]: value };
```

2022-08-06 07:48 UTC, tshemsedinov commented on lib/utilities.js
> +          );
```suggestion
          const error = `Can not combine keys: key "${newKey}" already exists`;
          throw new Error(error);
```

2022-08-06 08:00 UTC, tshemsedinov commented on test/utilities.js
> +metatests.test('Object: unflatFields exception', (test) => {
```suggestion
metatests.test('Object: unflatFields naming collision', (test) => {
```

2022-08-06 08:01 UTC, tshemsedinov commented on test/utilities.js
> +
```suggestion
```

2022-08-06 08:02 UTC, tshemsedinov commented on lib/utilities.js
> +    }
```suggestion
```

2022-08-06 08:07 UTC, tshemsedinov commented on lib/utilities.js
> +      const newKey = key.slice(prefix.length).toLowerCase();
```suggestion
      const newKey = key.substring(0, prefix.length).toLowerCase();
```

2022-08-06 08:15 UTC, tshemsedinov commented on lib/utilities.js
> +      if (Object.prototype.hasOwnProperty.call(sourceObject, prefix) {
```suggestion
      if (Object.prototype.hasOwnProperty.call(sourceObject, prefix)) {
```

2022-08-06 08:16 UTC, tshemsedinov commented on lib/utilities.js
> +const unflatObject = (sourceObject, fieldNames = []) => {
```suggestion
const unflatObject = (sourceObject, fieldNames) => {
```

2022-08-06 08:22 UTC, tshemsedinov commented on lib/utilities.js
> +      const newKey = key.substring(0, prefix.length).toLowerCase();
```suggestion
      const newKey = key.substring(prefix.length).toLowerCase();
```

2022-08-06 08:24 UTC, merged