Make `ensireDirectory` atomic
metarhia/metautil pull request #179
Opened 2023-07-25 09:32 UTC by tadjik1

- [x] tests and linter show no problems (`npm t`)
- [ ] tests are added/updated for bug fixes and new features
- [x] code is properly formatted (`npm run fmt`)
- [x] description of changes is added in CHANGELOG.md
- [ ] update .d.ts typings

2023-07-25 11:37 UTC, tshemsedinov requested changes

2023-07-25 11:37 UTC, tshemsedinov commented on lib/fs.js
> +  );
```suggestion
  return fsp.mkdir(path).then(() => true, (err) => err.code === 'EEXIST');
```

2023-07-25 19:47 UTC, tshemsedinov commented
Looks like we can't distinguish existing file `./LICENSE` and directory `./abc`

2023-07-26 12:50 UTC, tadjik1 commented
checked the tests, this is the tricky one, there is no difference between directory and folder, but the test assumes that `ensureDirectory` returns `false` when a file with the same name is presented. is it by design?

2023-07-26 14:01 UTC, tshemsedinov commented
@tadjik1 Why do we need `ensireDirectory` at all? We heed it to put files in it. So two cases are positive for us: if directory is already exists or if `ensireDirectory` can create it. Function will return true if we can put files in this directory, otherwise - false.

2023-07-29 15:08 UTC, tadjik1 commented
@tshemsedinov в таком случае без второго запроса не обойтись, текущее решение наиболее оптимальное. Закрою пр

2023-07-29 15:08 UTC, closed without merging

2023-07-29 15:41 UTC, tshemsedinov commented
@tadjik1 good try, sure that PR was an experimental and result was not known to me at the beginning, Thanks!